### ISSUE TITLE
Nintendo 64 Stick and C buttons BUG and more 2 issues

### ISSUE THREAD

**Issue by megamandev** [ethanaobrien/emulatorjs#95] opened 2022-01-19 18:30 UTC
1 > Nintendo 64 Stick and C buttons

Not work with usb controller, i tested all possibles settings and not work.
Work only with keyboard!

2 > MAME controller settings wrong

when I click on the mame control settings. appears the settings of the contorle of nintendo 64 and not the arcade as I can switch to arcade

3 > MAME roms not working

kinst > killer instinct
kinst2 > killer instinct 2
matrimnd > Power Instinct Matrimelee
tekken > tekken

**Comment by ethanaobrien** [comment] 2022-01-19 18:34
>Nintendo 64 Stick and C buttons

Duplicate of #93 

>MAME controller settings wrong

You need to map all the controls per system. This isnt a bug, as the default controls are the same for every system.

>MAME roms not working

Duplicate of #88, fix planned, just havent completed

**Comment by megamandev** [comment] 2022-01-19 18:38
@ethanaobrien 

You need to map all the controls per system. This isnt a bug, as the default controls are the same for every system.

no "mame" is different not have insert coin, habe only select and start

**Comment by ethanaobrien** [comment] 2022-01-19 18:39
>You need to map all the controls per system

This is correct

>no "mame" is different not have insert coin, habe only select and start

Are you saying mame needs an `insert coin` button?

**Comment by megamandev** [comment] 2022-01-19 18:50
@ethanaobrien 

yes need translate select button to Insert coin, because select works like Insert coin

print screen
arcade controller settings
https://ibb.co/RPSPRSP

mame controller settings
https://ibb.co/0jp0gKC

**Comment by ethanaobrien** [comment] 2022-01-19 18:52
Now thats something I can fix

**Comment by megamandev** [comment] 2022-01-19 18:53
once again thank you very much for your attention

**Comment by megamandev** [comment] 2022-01-19 19:24
"mame" don't have save state and load state buttons

print
https://ibb.co/bKksf47

**Comment by ethanaobrien** [comment] 2022-01-19 19:38
@megamandev Mame does not support save state and load state

**Comment by megamandev** [comment] 2022-01-19 19:40
ok.. you can add cores to mame to run this games

kinst > killer instinct #release by Rare
kinst2 > killer instinct 2 #release by Rare
matrimnd > Power Instinct Matrimelee #release by Neo Geo
tekken > tekken  #release by Nanco
tekken2 > tekken 2 #release by Nanco
btoads > battletoads #release by Rare

**Closed** 2022-01-23 22:39 UTC
